steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/health-agent-api:$BUILD_ID
      - -t
      - gcr.io/$PROJECT_ID/health-agent-api:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/health-agent-api:$BUILD_ID
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/health-agent-api:latest
images:
  - gcr.io/$PROJECT_ID/health-agent-api:$BUILD_ID
  - gcr.io/$PROJECT_ID/health-agent-api:latest
