steps:
  - name: node:20-bullseye
    entrypoint: bash
    args:
      - -lc
      - corepack enable && pnpm dlx prisma@5.22.0 migrate deploy --schema=apps/api/prisma/schema.prisma
    secretEnv:
      - DATABASE_URL
      - DATABASE_DIRECT_URL
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/finance-agent-api:$BUILD_ID
      - -t
      - gcr.io/$PROJECT_ID/finance-agent-api:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/finance-agent-api:$BUILD_ID
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/finance-agent-api:latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image
      - gcr.io/$PROJECT_ID/finance-agent-api:$BUILD_ID
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-secrets
      - DATABASE_URL=${_DATABASE_URL_SECRET}:latest,DATABASE_DIRECT_URL=${_DATABASE_DIRECT_URL_SECRET}:latest,AKAHU_APP_TOKEN=${_AKAHU_APP_TOKEN_SECRET}:latest,AKAHU_USER_TOKEN=${_AKAHU_USER_TOKEN_SECRET}:latest,INTERNAL_API_KEY=${_INTERNAL_API_KEY_SECRET}:latest,PIPELINE_TOKEN=${_PIPELINE_TOKEN_SECRET}:latest
      - --set-env-vars
      - API_PORT=8080,AKAHU_BASE_URL=${_AKAHU_BASE_URL},AKAHU_LOOKBACK_DAYS=${_AKAHU_LOOKBACK_DAYS},AKAHU_PAGE_SIZE=${_AKAHU_PAGE_SIZE}
      - --quiet
images:
  - gcr.io/$PROJECT_ID/finance-agent-api:$BUILD_ID
  - gcr.io/$PROJECT_ID/finance-agent-api:latest
substitutions:
  _SERVICE: finance-agent-api
  _REGION: australia-southeast1
  _DATABASE_URL_SECRET: finance-agent-database-url
  _DATABASE_DIRECT_URL_SECRET: finance-agent-database-direct-url
  _AKAHU_APP_TOKEN_SECRET: finance-agent-akahu-app-token
  _AKAHU_USER_TOKEN_SECRET: finance-agent-akahu-user-token
  _INTERNAL_API_KEY_SECRET: finance-agent-internal-api-key
  _PIPELINE_TOKEN_SECRET: finance-agent-pipeline-token
  _AKAHU_BASE_URL: https://api.akahu.io/v1
  _AKAHU_LOOKBACK_DAYS: "14"
  _AKAHU_PAGE_SIZE: "250"
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_URL_SECRET}/versions/latest
      env: DATABASE_URL
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_DIRECT_URL_SECRET}/versions/latest
      env: DATABASE_DIRECT_URL
